export const articles = [
  {
    slug: "google-ai-mode-seo-2026",
    category: "SEO · GEO · AEO · AIO",
    date: "23 Eylül 2026",
    dateISO: "2026-09-23",
    title: "Google AI Mode Türkiye’de: SEO, GEO, AEO ve AIO için 2026 rehberi",
    excerpt: "Google AI Mode ve AI Overviews döneminde markaların klasik sıralamanın ötesinde görünürlük kazanması için uygulanabilir 2026 rehberi.",
    image: "/images/blog/ai-arama-gorunurlugu.webp",
    inlineImage: "/images/blog/ai-arama-gorunurlugu-detail.webp",
    sections: [
      ["Google araması artık yalnızca on mavi bağlantıdan ibaret değil", "Google’ın Türkiye’de AI Mode ve AI Overviews deneyimini devreye alması, arama görünürlüğünün mantığını değiştirdi. Kullanıcı artık tek bir anahtar kelime yerine daha uzun, karşılaştırmalı ve karar odaklı sorular sorabiliyor. Bu nedenle markanın yalnızca bir kelimede sıralama alması yeterli değil; kim olduğu, hangi hizmeti verdiği, hangi bölgede çalıştığı, hangi sorunu çözdüğü ve bunu hangi kanıtlarla desteklediği de açık biçimde anlaşılmalı. 2026’da SEO çalışması teknik altyapı, içerik, marka varlığı ve yapılandırılmış veriyi birlikte ele almak zorunda."],
      ["SEO, GEO, AEO ve AIO arasındaki fark", "SEO klasik arama motorlarında taranabilirlik, indekslenebilirlik, içerik kalitesi ve organik sıralama tarafını kapsar. GEO üretken yapay zekâ sistemlerinin markayı doğru bağlamda anlayabilmesi ve gerektiğinde kaynak olarak değerlendirebilmesiyle ilgilidir. AEO kullanıcı sorularına doğrudan ve açık cevaplar üreten içerik mimarisini ifade eder. AIO ise yapay zekâ destekli arama yüzeylerinin tamamına uyum sağlayan daha geniş optimizasyon yaklaşımıdır. Bunlar birbirinden kopuk dört ayrı proje değil; aynı görünürlük sisteminin farklı katmanlarıdır."],
      ["AI cevaplarında görünür olmak için hangi sinyaller gerekir?", "Marka adı, şirket bilgileri, hizmet kapsamı, lokasyon, iletişim bilgileri, uzmanlık sayfaları, vaka çalışmaları ve sık sorulan sorular tutarlı olmalıdır. Hizmet sayfalarında genel sloganlar yerine gerçek kapsam anlatılmalı; örneğin ikas kurulumu denildiğinde ürün ve kategori yapısı, ödeme, kargo, ERP, pazaryeri, tasarım ve yayına alma süreçleri açıkça belirtilmelidir. Schema.org işaretlemeleri, breadcrumb yapısı, güncel sitemap ve güçlü iç linkleme makinelerin sayfalar arasındaki ilişkiyi anlamasını kolaylaştırır."],
      ["İçerik artık arama niyetine göre kümelenmeli", "Tek bir uzun sayfada her şeyi anlatmak yerine kullanıcıların gerçekten sorduğu konular için ayrı fakat birbirine bağlı içerikler üretmek daha sağlıklı sonuç verir. 'E-ticaret sitesi nasıl kurulur', 'ikas kurulum maliyeti', 'Shopify mı ikas mı', 'AI aramalarında nasıl görünürüm' gibi sorgular farklı niyetlere sahiptir. Bilgilendirici içerikten hizmet sayfasına, hizmet sayfasından vaka çalışmasına ve oradan iletişime uzanan mantıklı bir iç link yapısı kurulmalıdır."],
      ["2026 için uygulanabilir kontrol listesi", "Önce teknik tarama, canonical, sitemap, robots, Core Web Vitals ve mobil deneyim kontrol edilir. Ardından marka ve hizmet entity’leri netleştirilir, sayfa başlıkları arama niyetine göre yeniden yazılır, FAQ ve structured data eklenir, gerçek referanslarla güven sinyalleri güçlendirilir ve düzenli içerik üretimi başlatılır. Son adım GA4 ve Search Console verileriyle hangi sayfaların gösterim, tıklama ve dönüşüm ürettiğini izlemektir. Amaç yalnızca trafik değil, markayı doğru arama ve AI cevaplarında tercih edilebilir hale getirmektir."],
    ],
  },
  {
    slug: "ikas-e-ticaret-sitesi-kurma-2026",
    category: "ikas · E-ticaret",
    date: "23 Eylül 2026",
    dateISO: "2026-09-23",
    title: "ikas e-ticaret sitesi nasıl kurulur? 2026 başlangıç rehberi",
    excerpt: "ikas ile e-ticarete başlarken paket seçiminden domain, tasarım, ürün, ödeme, kargo ve pazaryeri entegrasyonlarına kadar izlenecek yol.",
    image: "/images/blog/platform-secimi.webp",
    inlineImage: "/images/blog/platform-secimi-detail.webp",
    sections: [
      ["ikas kurulumu paket satın almakla bitmez", "ikas üzerinden e-ticaret sitesi açmak teknik olarak hızlı olabilir; ancak satışa hazır bir mağaza için doğru kategori mimarisi, ürün verisi, görseller, ödeme yöntemleri, kargo kuralları, yasal sayfalar, domain, ölçüm ve tasarımın birlikte hazırlanması gerekir. En sık yapılan hata önce paketi almak, daha sonra mağazanın gerçek operasyon ihtiyaçlarını düşünmektir. Doğru sıra önce ihtiyaç haritası, sonra paket ve kurulum kararlarıdır."],
      ["İlk adım ürün ve operasyon haritasıdır", "Kaç ürün ve varyant olduğu, stokların nereden yönetileceği, hangi kargo firmalarının kullanılacağı, pazaryerlerinde satış olup olmadığı, ERP veya muhasebe entegrasyonu gerekip gerekmediği ve yurt dışı satış planının bulunup bulunmadığı yazılı hale getirilmelidir. Bu bilgiler tema seçiminden ürün aktarımına kadar pek çok kararı etkiler. Özellikle yüzlerce ürün içeren mağazalarda veri temizliği ve kategori standardı tasarımdan daha kritik hale gelebilir."],
      ["Tasarım satış akışını desteklemeli", "Ana sayfa yalnızca büyük bir banner ve ürün kartlarından oluşmamalıdır. Kategori girişleri, yeni gelenler, çok satanlar, kampanya alanları, güven unsurları ve mobil satın alma akışı ziyaretçiyi karar vermeye taşımalıdır. Ürün detayında beden, renk, varyant, kargo, iade ve ödeme bilgileri açık olmalıdır. Mobil menü, filtre ve sepete ekleme akışının sorunsuz çalışması doğrudan dönüşüm oranını etkiler."],
      ["Domain, ödeme, kargo ve ölçüm birlikte açılmalı", "Markanın kendi domaini doğru DNS ayarlarıyla bağlanmalı, ödeme altyapısı test edilmeli, kargo senaryoları gerçek sipariş akışıyla doğrulanmalı ve GA4 dönüşüm olayları yayından önce hazırlanmalıdır. WhatsApp tıklaması, sepete ekleme, ödeme başlangıcı ve satın alma gibi kritik davranışlar ölçülmediğinde site yayında olsa bile hangi adımın çalıştığını görmek zorlaşır."],
      ["Yayından önce final kontrol yapın", "Mobil ve masaüstünde ürün kartları, varyantlar, arama, filtre, sepet, ödeme, kupon, e-posta bildirimleri ve yasal sayfalar test edilmelidir. Search Console, sitemap ve temel structured data ayarları da yayına hazır olmalıdır. ikas mağazası kurulumunda hedef yalnızca siteyi açmak değil; ilk günden itibaren yönetilebilir, ölçülebilir ve büyümeye hazır bir satış sistemi kurmaktır."],
    ],
  },
  {
    slug: "e-ticaret-sitesi-maliyeti-2026",
    category: "E-ticaret maliyeti",
    date: "23 Eylül 2026",
    dateISO: "2026-09-23",
    title: "E-ticaret sitesi kurma maliyeti 2026: Gerçek bütçe nasıl hesaplanır?",
    excerpt: "2026’da e-ticaret sitesi maliyetini yalnızca paket fiyatıyla değil; tasarım, domain, ödeme, entegrasyon, içerik, reklam ve operasyonla birlikte hesaplayın.",
    image: "/images/blog/pazaryeri-kendi-site.webp",
    inlineImage: "/images/blog/pazaryeri-kendi-site-detail.webp",
    sections: [
      ["E-ticaret sitesi fiyatı neden tek rakam değildir?", "Bir e-ticaret sitesinin maliyeti kullanılan platform paketinden çok daha geniştir. Yazılım lisansı, tema veya özel tasarım, domain, ödeme kuruluşu kesintileri, ürün ve kategori aktarımı, görsel üretimi, ERP ve pazaryeri entegrasyonları, kargo bağlantıları, SEO, bakım ve reklam bütçesi toplam maliyeti oluşturur. Bu nedenle 'site kaç TL' sorusunun doğru cevabı, ihtiyaç listesi çıkarılmadan verilemez."],
      ["Sabit maliyet ile işlem maliyetini ayırın", "Domain, yıllık lisans, tasarım ve kurulum gibi kalemler sabit maliyet olarak düşünülebilir. Sanal POS komisyonu, kargo, reklam, iade ve pazaryeri komisyonu ise sipariş hacmine göre değişen maliyetlerdir. Sağlıklı bütçe çalışmasında bu iki grup ayrı hesaplanmalı ve sipariş başına gerçek maliyet görülmelidir. Aksi halde ucuz görünen bir altyapı yüksek işlem maliyetleriyle daha pahalı hale gelebilir."],
      ["Hazır tema mı, özel tasarım mı?", "Hazır tema hızlı ve düşük başlangıç maliyetli olabilir. Ancak marka farklılaşması, özel kullanıcı akışı veya yoğun kategori yapısı gerektiğinde tema üzerinde profesyonel düzenleme ihtiyacı doğar. Özel tasarım bütçesi yalnızca görsel kalite için değil; mobil deneyim, ürün keşfi, kampanya yerleşimi ve dönüşüm akışını markaya göre optimize etmek için değerlendirilmelidir."],
      ["Entegrasyonlar bütçeyi neden değiştirir?", "ERP, muhasebe, pazaryeri, kargo, CRM ve özel uygulama bağlantıları projenin teknik kapsamını büyütür. Hazır entegrasyon varsa maliyet daha öngörülebilirken, özel API geliştirmesi gerektiğinde analiz, geliştirme, test ve bakım süreleri hesaba katılır. Bu nedenle teklif alırken yalnızca ana sayfa ve ürün sayfası tasarımını değil, operasyonun arka planda nasıl çalışacağını da sormak gerekir."],
      ["2026 bütçesinde en önemli kriter toplam sahip olma maliyetidir", "Doğru karşılaştırma ilk kurulum fiyatı üzerinden değil, 12 aylık toplam sahip olma maliyeti üzerinden yapılır. Lisans, uygulamalar, geliştirme, bakım, reklam, ödeme kesintileri ve operasyon zamanı aynı tabloda değerlendirilmelidir. Ucuz başlangıç her zaman ucuz büyüme anlamına gelmez. En iyi yatırım, markanın bugünkü ihtiyacını karşılayıp yarınki büyümesini yeniden platform değiştirmeye zorlamayan altyapıdır."],
    ],
  },
  {
    slug: "e-ticaret-sitesi-nasil-kurulur-2026",
    category: "E-ticaret rehberi",
    date: "23 Eylül 2026",
    dateISO: "2026-09-23",
    title: "E-ticaret sitesi nasıl kurulur? 2026 için adım adım kontrol listesi",
    excerpt: "Şirket, domain, platform, ürün, ödeme, kargo, tasarım, SEO, GA4 ve güvenlik dahil 2026’da e-ticaret sitesi kurmanın temel adımları.",
    image: "/images/blog/donusum-odakli-web.webp",
    inlineImage: "/images/blog/donusum-odakli-web-detail.webp",
    sections: [
      ["Önce iş modelini netleştirin", "E-ticaret sitesi kurmaya tema seçerek başlamak yerine ürün, hedef müşteri, fiyatlandırma, stok, kargo ve iade modelini netleştirmek gerekir. Kendi stoğunuzdan mı satış yapacağınız, pazaryerleriyle birlikte mi ilerleyeceğiniz, yurt dışına satış planlayıp planlamadığınız ve kaç ürünle başlayacağınız altyapı kararını doğrudan etkiler. İş modeli net değilse teknik kurulum ilerledikçe yeniden iş çıkar."],
      ["Domain ve platform seçimini büyüme planına göre yapın", "Domain kısa, markayla uyumlu ve kolay yazılabilir olmalıdır. Platform tarafında ikas, Shopify veya WooCommerce gibi seçenekler ekip kapasitesi, entegrasyonlar, ürün sayısı, uluslararası satış ihtiyacı ve bütçeye göre karşılaştırılmalıdır. Bir platformu yalnızca aylık fiyatına göre seçmek yerine en az bir yıllık operasyon ve geliştirme ihtiyacıyla birlikte değerlendirmek daha sağlıklıdır."],
      ["Ürün verisi ve kategori yapısı SEO’nun temelidir", "Ürün isimleri, açıklamalar, varyantlar, renk ve beden bilgileri, görseller, kategori isimleri ve URL yapısı standart olmalıdır. Aynı ürünün farklı yerlerde farklı isimlerle kullanılması hem kullanıcı deneyimini hem arama görünürlüğünü zayıflatır. Kategori ağacı gerçek kullanıcı aramalarına göre kurulmalı; ürün açıklamaları kopya üretici metni yerine satın alma kararına yardımcı olacak özgün bilgiler içermelidir."],
      ["Ödeme, kargo, yasal metin ve güvenlik olmadan yayına çıkmayın", "Sanal POS veya ödeme sağlayıcısı gerçek test siparişiyle doğrulanmalı, kargo ücretleri ve ücretsiz kargo eşikleri kontrol edilmeli, mesafeli satış, iade, gizlilik, KVKK ve çerez metinleri projeye uygun hazırlanmalıdır. SSL, yönetici erişimi, güçlü şifreler ve mümkünse ek güvenlik katmanları yayından önce tamamlanmalıdır."],
      ["Yayın sonrası SEO ve ölçüm başlar", "Site açıldıktan sonra sitemap Search Console’a gönderilmeli, GA4 olayları doğrulanmalı ve organik gösterimler izlenmelidir. İlk haftalarda arama sorguları, kullanıcı davranışı, sepet terk oranı ve en çok ziyaret edilen ürünler yeni optimizasyon kararlarını verir. Başarılı e-ticaret sitesi bir defa tamamlanan tasarım değil; veri geldikçe geliştirilen yaşayan bir satış sistemidir."],
    ],
  },
  {
    slug: "pazaryeri-mi-kendi-e-ticaret-siteniz-mi",
    category: "E-ticaret stratejisi",
    date: "9 Eylül 2026",
    dateISO: "2026-09-09",
    title: "Pazaryeri mi, kendi e-ticaret siteniz mi?",
    excerpt: "Komisyon, müşteri verisi, reklam maliyeti ve marka kontrolünü birlikte değerlendiren karar çerçevesi.",
    image: "/images/blog/pazaryeri-kendi-site.webp",
    inlineImage: "/images/blog/pazaryeri-kendi-site-detail.webp",
    sections: [
      ["Soruyu satıştan önce kârlılık belirler", "Pazaryerleri markalara hazır trafik, tanınmış ödeme akışı ve kullanıcı güveni sunar. Bu yüzden özellikle yeni başlayan markalar için hızlı satış almak cazip görünür. Fakat tabloyu yalnızca ciro üzerinden okumak yanıltıcıdır. Komisyon, zorunlu kampanya katılımı, reklam maliyeti, iade oranı, kargo şartları ve fiyat rekabeti hesaba katıldığında bazı ürünlerde yüksek satış hacmi düşük net kâra dönüşebilir. Kendi e-ticaret siteniz ise trafik üretme sorumluluğunu size verir; buna karşılık müşteri verisi, marka algısı, tekrar satın alma ve fiyat kontrolü üzerinde çok daha güçlü bir alan açar."],
      ["Gerçek maliyet tablosunu çıkarın", "Doğru karar için ürün maliyeti, pazaryeri komisyonu, ödeme kuruluşu kesintisi, reklam gideri, kargo, paketleme, iade, yazılım, personel ve operasyon yükünü sipariş başına hesaplamak gerekir. Bir platformun aylık paket ücreti düşük diye toplam maliyetinin düşük olduğunu varsaymak doğru değildir. Aynı şekilde pazaryeri komisyonu yüksek diye pazaryerini tamamen dışlamak da doğru olmayabilir. Önemli olan her kanalın net katkısını ayrı görmek ve hangi ürün grubunun hangi kanalda daha sağlıklı büyüdüğünü ölçmektir."],
      ["Müşteri verisi stratejik avantajdır", "Pazaryerinde müşteri çoğu zaman platformun müşterisidir; markanızla kurduğu bağ sınırlı kalabilir. Kendi mağazanızda ise e-posta, telefon, davranış verisi, sepet terk etme bilgisi ve tekrar satın alma sinyalleri size aittir. Bu veriler doğru izin ve KVKK süreçleriyle yönetildiğinde, marka sadakati ve yeniden pazarlama için ciddi avantaj sağlar. Kısa vadede pazaryeri hızlı hacim getirebilir; uzun vadede kendi siteniz markanın dijital varlığını büyüten merkez olur."],
      ["Hibrit yapı çoğu marka için daha sağlıklıdır", "Pazaryeri ve kendi siteniz birbirinin alternatifi olmak zorunda değildir. Birçok marka pazaryerlerini keşif ve hacim kanalı, kendi mağazasını ise sadakat, özel kampanya, yeni koleksiyon ve marka deneyimi merkezi olarak kullanır. Burada kritik olan stok, fiyat, kampanya ve ürün seçimini bilinçli ayırmaktır. Her yerde aynı fiyat ve aynı kampanya yapıldığında kendi sitenizin tercih edilmesi zorlaşır. Özel paketler, sadakat avantajları, hızlı destek ve daha güçlü içerikle kendi mağazanızın nedeni netleşmelidir."],
      ["Karar tek seferlik değil, düzenli ölçülen bir sistemdir", "Platform kararı bir defa verilip unutulacak bir konu değildir. Reklam maliyetleri, komisyon oranları, kategori rekabeti ve tüketici davranışı değiştikçe kanal kârlılığı da değişir. Bu yüzden aylık olarak net kâr, dönüşüm oranı, tekrar satın alma, sepet ortalaması ve iade oranı izlenmelidir. Kanal kârlılığı analizi de tam olarak buradan başlar: satış aynı kalsa bile, kanal yapısı değiştiğinde markanın elinde kalan para ciddi şekilde farklılaşabilir."],
    ],
  },
  {
    slug: "shopify-ikas-woocommerce-nasil-secilir",
    category: "Platform seçimi",
    date: "7 Eylül 2026",
    dateISO: "2026-09-07",
    title: "Shopify, ikas ve WooCommerce nasıl seçilir?",
    excerpt: "Platform isimlerinden önce ekip, operasyon, büyüme planı ve toplam sahip olma maliyetini değerlendirin.",
    image: "/images/blog/platform-secimi.webp",
    inlineImage: "/images/blog/platform-secimi-detail.webp",
    sections: [
      ["En iyi platform diye tek bir cevap yoktur", "Shopify, ikas ve WooCommerce farklı ihtiyaçlara güçlü cevaplar verir. Shopify yönetilebilir altyapısı, uygulama ekosistemi ve uluslararası satış kabiliyetiyle öne çıkar. ikas Türkiye pazarına yakın operasyon ihtiyaçları, hızlı kurulum yapısı ve yerel e-ticaret alışkanlıklarına uygun çözümleriyle güçlüdür. WooCommerce ise WordPress esnekliği, içerik yönetimi ve özelleştirme özgürlüğü isteyen markalar için avantaj sağlar. Bu nedenle karar platformun popülerliğine göre değil, markanın gerçek operasyonuna göre verilmelidir."],
      ["Ekip kapasitesi toplam maliyeti değiştirir", "Teknik özgürlük ancak onu yönetecek ekip varsa avantajdır. WooCommerce çok esnek olabilir; fakat güncelleme, güvenlik, eklenti uyumu, hız ve bakım süreçleri düzenli takip ister. Shopify ve ikas daha yönetilebilir bir yapı sunabilir; ancak uygulama, abonelik, tema ve entegrasyon maliyetleri doğru planlanmalıdır. Küçük ekipler için sade yönetim büyük avantajken, özel ihtiyaçları yoğun olan markalar için geliştirilebilir yapı daha doğru olabilir."],
      ["Operasyon haritası çıkarılmadan platform seçilmez", "Ürün sayısı, varyant yapısı, ülke ve para birimleri, kargo senaryoları, ödeme yöntemleri, B2B ihtiyacı, pazaryeri bağlantıları, ERP/muhasebe entegrasyonu, kampanya kurguları ve içerik üretim planı yazılı hale getirilmelidir. Platform kararı bu listenin ardından netleşir. Aksi halde marka önce siteyi kurar, sonra gerçek ihtiyaçlar ortaya çıktığında pahalı revizyonlarla uğraşır."],
      ["Tasarım kadar yönetilebilirlik de önemlidir", "E-ticaret sitesi yalnızca güzel görünmek için kurulmaz; günlük olarak ürün eklenir, kampanya açılır, stok takip edilir, sipariş yönetilir ve içerik güncellenir. Panel karmaşıksa ekip siteyi kullanmaktan kaçınır. Bu yüzden seçilecek altyapı markanın operasyon alışkanlıklarıyla uyumlu olmalıdır. Premium deneyim yalnızca ön yüzde değil, markanın siteyi rahat yönetmesinde de başlar."],
      ["Doğru karar büyüme planıyla birlikte verilir", "Bugün 100 ürün satan bir mağazanın ihtiyacı ile yarın yurt dışına açılacak, çok dilli, çok para birimli ve pazaryeri entegre çalışan bir markanın ihtiyacı aynı değildir. Platform seçimi markanın bugünkü yükünü hafifletmeli ama yarınki büyümesini de kilitlememelidir. Olivon bu yüzden platform seçimini tasarım kararından önce strateji, maliyet ve operasyon başlığıyla birlikte ele alır."],
    ],
  },
  {
    slug: "yapay-zeka-aramalarinda-marka-gorunurlugu",
    category: "SEO · GEO · AEO",
    date: "4 Eylül 2026",
    dateISO: "2026-09-04",
    title: "Yapay zekâ aramalarında markanız nasıl anlaşılır?",
    excerpt: "Görünürlük artık sıralamadan ibaret değil; marka, hizmet ve uzmanlık ilişkilerinin açık olması gerekiyor.",
    image: "/images/blog/ai-arama-gorunurlugu.webp",
    inlineImage: "/images/blog/ai-arama-gorunurlugu-detail.webp",
    sections: [
      ["Varlık netliği yeni temeldir", "Arama deneyimi yalnızca klasik sonuç sayfasından ibaret değil. Kullanıcılar artık Google, yapay zekâ cevap motorları, harita sonuçları, sosyal platformlar ve pazaryerleri arasında karar veriyor. Bu ortamda markanızın kim olduğu, nerede hizmet verdiği, hangi konuda uzmanlaştığı ve hangi kanallardan doğrulanabildiği net olmalıdır. Marka adı, hizmetler, lokasyon, iletişim bilgileri, referanslar ve içerik dili farklı yerlerde çelişirse sistemler markanızı güvenilir biçimde anlamakta zorlanır."],
      ["Sayfalar cevap üretmeye uygun olmalı", "SEO uyumlu sayfa yalnızca anahtar kelime geçen sayfa değildir. İyi bir sayfa kullanıcının gerçek sorusuna net cevap verir, ardından karar vermesi için yeterli derinlik sunar. Örneğin ikas web sitesi kurulumu arayan biri yalnızca fiyat görmek istemez; süreç, teslim kapsamı, entegrasyonlar, ürün girişi, kargo, ödeme, destek ve yayına alma adımlarını da anlamak ister. Yapay zekâ sistemleri de bu açık ve düzenli bilgileri daha kolay yorumlar."],
      ["GEO, AEO ve AIO birlikte düşünülmeli", "GEO markanın üretken yapay zekâ cevaplarında nasıl konumlandığıyla, AEO doğrudan cevap motorlarına uygun içerik yapısıyla, AIO ise yapay zekâ destekli arama deneyimlerine uyumla ilgilidir. Bunları klasik SEO’dan ayrı bir moda gibi görmek yerine aynı görünürlük sisteminin parçaları olarak değerlendirmek gerekir. Teknik yapı, içerik mimarisi, schema verileri, referanslar ve marka güven sinyalleri birlikte çalışmalıdır."],
      ["Yerel güven sinyalleri Türkiye pazarında kritiktir", "Türkiye odaklı çalışan markalarda lokasyon, telefon, e-posta, açık hizmet kapsamı ve gerçek referanslar karar sürecini hızlandırır. Kayseri merkezli bir ajansın Türkiye geneline hizmet verdiğini anlatması, hem yerel hem ulusal aramalarda doğru sinyal üretir. Kullanıcı bir ajans sitesine girdiğinde markanın gerçek, ulaşılabilir ve iş bitirebilir olduğunu hissetmelidir."],
      ["İçerik düzenli güncellenmelidir", "Bir defa yazılan birkaç hizmet sayfası uzun vadede yeterli olmaz. Blog yazıları, vaka analizleri, sık sorulan sorular, karşılaştırma içerikleri ve hizmet detayları markanın uzmanlığını sürekli besler. Bu içerikler reklamdan bağımsız organik güven üretir. Olivon’un blog yapısı bu yüzden sadece haber alanı değil, potansiyel müşterinin karar sürecini olgunlaştıran bir bilgi katmanı olarak kurgulanır."],
    ],
  },
  {
    slug: "e-ticaret-sitesinde-guvenlik-kontrol-listesi",
    category: "Dijital güvenlik",
    date: "1 Eylül 2026",
    dateISO: "2026-09-01",
    title: "E-ticaret sitesi için güvenlik kontrol listesi",
    excerpt: "WAF’tan erişim yetkilerine kadar satış sürekliliğini koruyan temel güvenlik katmanları.",
    image: "/images/blog/e-ticaret-guvenlik.webp",
    inlineImage: "/images/blog/e-ticaret-guvenlik-detail.webp",
    sections: [
      ["Güvenlik satış sürekliliğidir", "E-ticaret güvenliği yalnızca saldırı olursa gündeme alınacak teknik bir konu değildir. Site yavaşladığında, ödeme akışı bozulduğunda, bot trafik stokları etkilediğinde veya yönetici paneli risk altına girdiğinde doğrudan satış kaybı yaşanır. Bu yüzden güvenlik; tasarım, hız, altyapı ve operasyonla birlikte düşünülmelidir. Premium bir mağaza yalnızca güzel görünen değil, kesintiye dayanıklı olan mağazadır."],
      ["Saldırı yüzeyini küçültün", "Kullanılmayan eklentiler, eski temalar, gereksiz yönetici hesapları, açık test sayfaları ve zayıf şifreler en sık risk kaynaklarıdır. Yönetim panelleri çok faktörlü kimlik doğrulama, rol bazlı yetki ve gerektiğinde IP veya erişim politikalarıyla sınırlandırılmalıdır. Her kullanıcıya tam yetki vermek operasyonu kolaylaştırıyor gibi görünür; fakat hata ve ihlal riskini büyütür."],
      ["Trafiği katmanlı yönetin", "Cloudflare gibi güvenlik katmanları DDoS koruması, WAF, bot yönetimi, hız sınırlama ve önbellekleme tarafında güçlü avantaj sağlar. Ancak her kural bilinçli yazılmalıdır. Fazla sert güvenlik gerçek müşteriyi engelleyebilir, fazla gevşek güvenlik ise saldırı trafiğini içeri alabilir. Amaç yalnızca engellemek değil, doğru trafiği koruyarak satış akışını açık tutmaktır."],
      ["Yedekleme ve geri dönüş test edilmeli", "Yedek almak tek başına güvenlik değildir. Yedeğin gerçekten geri dönebildiği, ne kadar sürede döndüğü ve hangi veriyi kapsadığı düzenli olarak kontrol edilmelidir. Ürün, sipariş, müşteri, görsel ve tema dosyalarının ayrı ayrı nasıl korunacağı bilinmelidir. Kritik bir kesinti anında kimin hangi adımı atacağı önceden belirlenmemişse, en iyi yedek bile geç devreye alınabilir."],
      ["Güvenlik marka algısını da etkiler", "Kullanıcı ödeme sayfasında hata görürse, site güvensiz uyarısı verirse veya sayfa sürekli yavaşlarsa markaya duyduğu güven azalır. Bu nedenle SSL, yönlendirmeler, güvenli ödeme akışı, hızlı açılan sayfalar ve net çerez/KVKK metinleri bir bütün olarak ele alınmalıdır. Olivon’un güvenlik başlığını ayrı sunmasının nedeni de budur: iyi ajans işi yalnızca tasarımda değil, altyapının sağlamlığında görünür."],
    ],
  },
  {
    slug: "donusum-odakli-web-sitesi-ne-demek",
    category: "Web deneyimi",
    date: "28 Ağustos 2026",
    dateISO: "2026-08-28",
    title: "Dönüşüm odaklı web sitesi gerçekten ne demek?",
    excerpt: "Daha fazla düğme değil; teklif, güven ve karar yolculuğunun doğru sırada sunulması.",
    image: "/images/blog/donusum-odakli-web.webp",
    inlineImage: "/images/blog/donusum-odakli-web-detail.webp",
    sections: [
      ["İlk ekranın tek görevi vardır", "Ziyaretçi siteye girdiğinde birkaç saniye içinde kimin için ne yaptığınızı, neden farklı olduğunuzu ve bir sonraki adımın ne olduğunu anlamalıdır. Büyük başlık güzel olabilir; fakat teklif net değilse dönüşüm üretmez. Ajans sitelerinde özellikle hizmet dili, referanslar, uzmanlık ve iletişim akışı ilk andan itibaren güven vermelidir. Kullanıcı tasarımın yapay durduğunu hissederse daha okumadan uzaklaşabilir."],
      ["Dönüşüm daha fazla buton demek değildir", "Her yere teklif al, hemen ara, WhatsApp’a yaz gibi butonlar koymak dönüşüm stratejisi değildir. Dönüşüm, ziyaretçinin karar vermesini kolaylaştıran doğru sıralamadır. Önce ne yaptığınızı anlar, sonra örnekleri görür, ardından süreci ve güven sinyallerini değerlendirir, en sonunda iletişime geçer. Bu yolculuk doğal akmadığında site kalabalık görünür ama ikna gücü düşer."],
      ["Güven tasarımın içinde kurulmalıdır", "Gerçek çalışmalar, canlı referanslar, açık hizmet kapsamı, partnerlikler, yasal sayfalar, iletişim bilgileri ve tutarlı görsel kalite birlikte güven üretir. Bir ajans sitesi yalnızca animasyonla premium olmaz. Animasyonlar içeriği güçlendirdiğinde etkili olur; içeriğin önüne geçtiğinde yapay görünür. Bu yüzden Olivon kurgusunda referans ekran görüntüleri, partner logoları, güvenlik başlığı ve süreç anlatımı aynı hikâyeyi destekler."],
      ["Mobil deneyim kararın büyük kısmını taşır", "Potansiyel müşteri çoğu zaman siteye telefondan bakar. Başlıkların taşması, butonların sıkışması, görsellerin kırpılması veya footer’ın dağınık durması marka algısını hızlı bozar. Mobilde elit görünüm, gereksiz küçültme değil; doğru kırılım, nefes alan boşluk, okunabilir metin ve dokunması kolay aksiyonlar demektir. Masaüstünde etkileyici olan bir bölüm mobilde aynı mantıkla değil, yeniden dengelenerek çalışmalıdır."],
      ["Ölçülmeyen deneyim geliştirilemez", "Form başlangıcı, WhatsApp tıklaması, telefon araması, referans sayfası görüntüleme, blog okuma ve teklif talebi gibi davranışlar anlamlı olaylar olarak izlenmelidir. Bu veriler hangi sayfanın ikna ettiğini, hangi başlığın çalıştığını ve hangi hizmetin daha çok talep aldığını gösterir. Dönüşüm odaklı web sitesi, yayına girdikten sonra da gerçek kullanıcı verisiyle gelişmeye devam eden sitedir."],
    ],
  },
] as const;
