export const caseStudies = [
  {
    slug: "oyku-baby-store",
    name: "Öykü Baby Store",
    domain: "oykubabystore.com.tr",
    url: "https://oykubabystore.com.tr/",
    image: "/references/oyku-baby-store.png",
    category: "Bebek & çocuk giyim",
    summary: "Ürün keşfini, kategori akışını ve marka vitrini deneyimini daha bütünlüklü hale getiren e-ticaret çalışması.",
    challenge: "Geniş ürün yapısını müşterinin hızlı tarayabileceği, güven veren ve mobilde güçlü çalışan bir vitrin deneyimi içinde toplamak.",
    work: ["E-ticaret bilgi mimarisi", "Kategori ve ürün sunumu", "Mobil vitrin deneyimi", "Marka dili ve görsel hiyerarşi"],
    deliverables: ["Bilgi mimarisi ve navigasyon kurgusu", "Kategori ve ürün vitrin düzeni", "Mobil responsive alışveriş akışı", "Canlı mağazada yayınlanan arayüz düzenlemeleri"],
    outcome: "Markanın ürünlerini daha düzenli sunabildiği, kategori keşfini kolaylaştıran ve kendi satış kanalını merkeze alan daha tutarlı bir e-ticaret deneyimi oluşturuldu.",
    evidence: "Canlı proje ve mevcut mağaza deneyimi üzerinden bilgi mimarisi, kategori yapısı, mobil vitrin ve yayınlanmış arayüz doğrulanabilir. Ticari metrikler müşteri verisi olduğu için bu sayfada yayınlanmıyor.",
    technology: ["E-ticaret altyapısı", "Responsive arayüz", "Ürün/kategori mimarisi"],
  },
  {
    slug: "bailas-kids",
    name: "Bailas Kids",
    domain: "bailaskids.com",
    url: "https://bailaskids.com/",
    image: "/references/bailas-kids.png",
    category: "Çocuk giyim",
    summary: "Premium marka algısını satış yolculuğuyla birleştiren, kategori ve ürün keşfine odaklanan e-ticaret vitrini.",
    challenge: "Görsel olarak güçlü koleksiyon sunumunu alışveriş akışını yavaşlatmadan, mobilde kolay taranabilir ve ticari olarak anlaşılır hale getirmek.",
    work: ["Premium vitrin kurgusu", "Kategori akışı", "Satış odaklı arayüz", "Mobil deneyim düzeni"],
    deliverables: ["Koleksiyon ve vitrin hiyerarşisi", "Kategori keşif akışı", "Mobil ürün keşif düzeni", "Canlı mağazada yayınlanan satış odaklı arayüz"],
    outcome: "Marka estetiği ile ürün keşfini aynı akışta birleştiren, ziyaretçiyi koleksiyondan ürüne daha net taşıyan bütünlüklü bir vitrin yapısı oluşturuldu.",
    evidence: "Canlı proje üzerinden koleksiyon sunumu, kategori akışı, mobil davranış ve yayınlanmış arayüz doğrulanabilir. Satış ve dönüşüm verileri kamuya açık olmadığı için oran paylaşılmıyor.",
    technology: ["E-ticaret altyapısı", "Responsive tasarım", "Dönüşüm odaklı UI"],
  },
  {
    slug: "favorim-kids",
    name: "Favorim Kids",
    domain: "favorimkids.com",
    url: "https://favorimkids.com/",
    image: "/references/favorim-kids.png",
    category: "Çocuk giyim & kombin",
    summary: "Kombin ve ürün çeşitliliğini daha okunabilir hale getiren, görsel düzen ve alışveriş yolculuğuna odaklanan e-ticaret deneyimi.",
    challenge: "Yoğun ürün ve kombin yapısını ziyaretçinin karar vermesini zorlaştırmadan sergilemek, marka sunumunu satış akışıyla daha sıkı bağlamak.",
    work: ["E-ticaret kurgu", "Görsel düzen", "Alışveriş yolculuğu", "Mobil içerik hiyerarşisi"],
    deliverables: ["Ürün ve kombin içerik hiyerarşisi", "Vitrin ve kategori düzeni", "Mobil içerik önceliklendirmesi", "Canlı mağazada yayınlanan alışveriş akışı"],
    outcome: "Ürün ve kombinlerin daha anlaşılır sunulduğu, görsel yoğunluğu kontrol eden ve müşteriyi alışveriş adımlarına daha net yönlendiren bir yapı ortaya çıkarıldı.",
    evidence: "Kamuya açık canlı mağaza üzerinden ürün/kombin sunumu, mobil içerik düzeni ve alışveriş akışı incelenebilir. Finansal ve analitik sonuçlar müşteri mahremiyeti nedeniyle yayınlanmıyor.",
    technology: ["E-ticaret altyapısı", "Responsive arayüz", "İçerik ve vitrin mimarisi"],
  },
  {
    slug: "recep-bozkurt",
    name: "Recep Bozkurt",
    domain: "recepbozkurt.com",
    url: "https://recepbozkurt.com/",
    image: null,
    category: "WooCommerce e-ticaret",
    summary: "WooCommerce altyapısı, ürün-kategori kurgusu ve satış akışını tek sistemde birleştiren uçtan uca e-ticaret kurulumu.",
    challenge: "Markanın dijital satış kanalını; ürünlerin düzenli yönetildiği, mobilde güven veren ve sipariş sürecini taşıyabilecek bir WooCommerce yapısı üzerinde kurmak.",
    work: ["WooCommerce altyapı kurulumu", "Ürün ve kategori mimarisi", "Sepet ve satış akışı", "Mobil arayüz ve yayına alma"],
    deliverables: ["WordPress ve WooCommerce kurulum yapısı", "Ürün/kategori yönetim mimarisi", "Sepet ve sipariş akışı", "Responsive arayüz ve canlı yayına alma"],
    outcome: "Markanın kendi alan adı üzerinde ürün yönetimi, alışveriş ve sipariş akışını tek merkezde yürütebildiği, geliştirmeye açık bir e-ticaret kanalı devreye alındı.",
    evidence: "Projenin canlı mağazası recepbozkurt.com üzerinden altyapı, ürün/kategori yapısı ve kullanıcı akışı incelenebilir. Satış tutarı ve dönüşüm oranı gibi özel ticari metrikler yayınlanmıyor.",
    technology: ["WordPress", "WooCommerce", "Responsive e-ticaret arayüzü", "Ürün/kategori ve satış akışı"],
  },
] as const;
