export const caseStudies = [
  {
    slug: "oyku-baby-store",
    name: "Öykü Baby Store",
    domain: "oykubabystore.com.tr",
    url: "https://oykubabystore.com.tr/",
    image: "/images/references/oyku-baby-store.png?v=20260910-1",
    category: "Bebek & çocuk giyim",
    summary: "Ürün keşfini, kategori akışını ve marka vitrini deneyimini daha bütünlüklü hale getiren e-ticaret çalışması.",
    challenge: "Geniş ürün yapısını müşterinin hızlı tarayabileceği, güven veren ve mobilde güçlü çalışan bir vitrin deneyimi içinde toplamak.",
    work: ["E-ticaret bilgi mimarisi", "Kategori ve ürün sunumu", "Mobil vitrin deneyimi", "Marka dili ve görsel hiyerarşi"],
    outcome: "Markanın ürünlerini daha düzenli sunabildiği, kategori keşfini kolaylaştıran ve kendi satış kanalını merkeze alan daha tutarlı bir e-ticaret deneyimi oluşturuldu.",
    evidence: "Canlı proje ve mevcut mağaza deneyimi üzerinden doğrulanabilir. Ticari metrikler müşteri verisi olduğu için bu sayfada yayınlanmıyor.",
    technology: ["E-ticaret altyapısı", "Responsive arayüz", "Ürün/kategori mimarisi"],
  },
  {
    slug: "bailas-kids",
    name: "Bailas Kids",
    domain: "bailaskids.com",
    url: "https://bailaskids.com/",
    image: "/images/references/bailas-kids.png?v=20260910-1",
    category: "Çocuk giyim",
    summary: "Premium marka algısını satış yolculuğuyla birleştiren, kategori ve ürün keşfine odaklanan e-ticaret vitrini.",
    challenge: "Görsel olarak güçlü koleksiyon sunumunu alışveriş akışını yavaşlatmadan, mobilde kolay taranabilir ve ticari olarak anlaşılır hale getirmek.",
    work: ["Premium vitrin kurgusu", "Kategori akışı", "Satış odaklı arayüz", "Mobil deneyim düzeni"],
    outcome: "Marka estetiği ile ürün keşfini aynı akışta birleştiren, ziyaretçiyi koleksiyondan ürüne daha net taşıyan bütünlüklü bir vitrin yapısı oluşturuldu.",
    evidence: "Canlı proje üzerinden tasarım ve kullanıcı akışı doğrulanabilir. Satış ve dönüşüm verileri kamuya açık olmadığı için oran paylaşılmıyor.",
    technology: ["E-ticaret altyapısı", "Responsive tasarım", "Dönüşüm odaklı UI"],
  },
  {
    slug: "favorim-kids",
    name: "Favorim Kids",
    domain: "favorimkids.com",
    url: "https://favorimkids.com/",
    image: "/images/references/favorim-kids.png?v=20260910-1",
    category: "Çocuk giyim & kombin",
    summary: "Kombin ve ürün çeşitliliğini daha okunabilir hale getiren, görsel düzen ve alışveriş yolculuğuna odaklanan e-ticaret deneyimi.",
    challenge: "Yoğun ürün ve kombin yapısını ziyaretçinin karar vermesini zorlaştırmadan sergilemek, marka sunumunu satış akışıyla daha sıkı bağlamak.",
    work: ["E-ticaret kurgu", "Görsel düzen", "Alışveriş yolculuğu", "Mobil içerik hiyerarşisi"],
    outcome: "Ürün ve kombinlerin daha anlaşılır sunulduğu, görsel yoğunluğu kontrol eden ve müşteriyi alışveriş adımlarına daha net yönlendiren bir yapı ortaya çıkarıldı.",
    evidence: "Kamuya açık canlı mağaza üzerinden sunum ve akış incelenebilir. Finansal ve analitik sonuçlar müşteri mahremiyeti nedeniyle yayınlanmıyor.",
    technology: ["E-ticaret altyapısı", "Responsive arayüz", "İçerik ve vitrin mimarisi"],
  },
] as const;
