import type { Locale } from "@/lib/i18n";

export type IntlPageKey = "services" | "ecommerce" | "search" | "web" | "security" | "work" | "faq" | "contact";

type IntlPage = {
  slug: string;
  title: string;
  metaTitle: string;
  metaDescription: string;
  kicker: string;
  lead: string;
  sections: Array<{ title: string; text: string; bullets?: string[] }>;
  faq?: Array<[string, string]>;
};

export const intlPages: Record<Locale, Record<IntlPageKey, IntlPage>> = {
  en: {
    services: { slug:"services", title:"Digital growth services for international brands", metaTitle:"Digital Growth Services | Olivon", metaDescription:"E-commerce, web design, SEO, GEO, AEO, AIO, automation and Cloudflare security for brands growing across markets.", kicker:"CAPABILITIES", lead:"We connect strategy, commerce, visibility, measurement and security into one accountable delivery system.", sections:[{title:"Commerce infrastructure",text:"Shopify, ikas and WooCommerce projects designed around product architecture, payments, shipping, ERP, marketplaces and measurable conversion paths.",bullets:["Platform setup and redesign","Cross-border commerce","SEO-safe platform migration","Payments, logistics and ERP integrations"]},{title:"Search and AI visibility",text:"Technical SEO, content architecture, structured data and entity signals built for Google and AI-assisted discovery.",bullets:["SEO","GEO","AEO","AIO"]},{title:"Web, automation and security",text:"Premium websites, controlled automation workflows and Cloudflare-first security for business-critical digital properties."}] },
    ecommerce: { slug:"cross-border-ecommerce", title:"Cross-border e-commerce built for operational reality", metaTitle:"Cross-border E-commerce & Platform Migration | Olivon", metaDescription:"Shopify, ikas and WooCommerce architecture, international store launches and SEO-safe migrations with payments, shipping, ERP and marketplace integrations.", kicker:"E-COMMERCE", lead:"International selling needs more than translated storefront copy. We align platform, catalog, logistics, payment, tax-facing UX and search migration before launch.", sections:[{title:"Platform architecture",text:"We define catalog structure, markets, currencies, customer journeys and the integration layer before theme work begins."},{title:"Migration without avoidable search loss",text:"Redirect mapping, canonical checks, metadata transfer, indexation control and post-launch crawl validation are treated as part of the migration, not an afterthought."},{title:"Commercial integrations",text:"Payments, shipping, ERP, marketplaces, analytics and operational handoffs are planned around the target market and existing business systems."}], faq:[["Can you migrate from another e-commerce platform?","Yes. We plan product, category, media and SEO migration together, with redirects and post-launch validation."],["Do you support Shopify, ikas and WooCommerce?","Yes. Platform choice is based on operating model, integration needs, team capability and target markets."],["Can one store serve multiple countries?","Yes, where the platform and operating model support it. We design language, currency and market-specific journeys accordingly."]] },
    search: { slug:"seo-geo-aeo-aio", title:"SEO, GEO, AEO & AIO as one visibility system", metaTitle:"SEO, GEO, AEO & AIO Services | Olivon", metaDescription:"Technical SEO, structured data, entity signals, answer-focused content and AI search visibility for international brands.", kicker:"SEARCH & AI VISIBILITY", lead:"We structure websites so search engines and answer systems can understand what the brand is, what it offers, where it operates and why it is relevant.", sections:[{title:"Technical SEO",text:"Crawlability, indexation, canonicalization, internal linking, sitemap hygiene, metadata, performance and structured data form the technical base."},{title:"GEO and entity clarity",text:"Brand, service and expertise signals are made explicit through consistent entities, organization data, topical coverage and citation-friendly information architecture."},{title:"AEO and answer architecture",text:"Key commercial questions are answered directly, supported by FAQ and service schema where appropriate, without creating thin or repetitive pages."},{title:"AIO readiness",text:"Content is written to remain useful in AI-assisted discovery: clear definitions, specific capabilities, evidence, market context and machine-readable relationships."}], faq:[["Is GEO separate from SEO?","We treat GEO as an extension of strong technical SEO and entity clarity rather than as a substitute for search fundamentals."],["Do you guarantee AI mentions?","No responsible provider can guarantee third-party AI citations. We improve the technical and content signals that make accurate discovery more likely."],["Do you implement schema markup?","Yes. We use relevant Organization, WebSite, WebPage, Service, Breadcrumb and FAQ structured data where it accurately represents the page."]] },
    web: { slug:"web-design", title:"Premium web design with commercial structure underneath", metaTitle:"Premium Web Design & Development | Olivon", metaDescription:"Premium corporate and commerce websites with mobile UX, performance, accessibility, conversion architecture and technical SEO foundations.", kicker:"WEB DESIGN & DEVELOPMENT", lead:"The visual layer matters, but the system underneath decides whether a website remains fast, understandable and useful as the business grows.", sections:[{title:"Information architecture first",text:"Navigation, page hierarchy, calls to action and proof points are designed around user intent before visual polish."},{title:"Performance and mobile UX",text:"Responsive behavior, media handling, interaction weight and layout stability are reviewed as product requirements."},{title:"Search-ready delivery",text:"Metadata, semantic headings, structured data, crawl paths and analytics hooks are included in the delivery model."}] },
    security: { slug:"digital-security", title:"Digital security for sites that need to stay available", metaTitle:"Cloudflare & Digital Security Services | Olivon", metaDescription:"Cloudflare, WAF, DDoS protection, bot control, access policies and monitoring for commerce and business-critical websites.", kicker:"DIGITAL SECURITY", lead:"Security should reduce operational risk without breaking customer journeys or legitimate traffic.", sections:[{title:"Cloudflare edge protection",text:"DNS, SSL, WAF, rate controls and traffic policies are configured to the actual risk and application behavior."},{title:"Bot and abuse controls",text:"Automated traffic is segmented so obvious abuse can be reduced while search engines and legitimate services remain accessible."},{title:"Access and continuity",text:"Administrative access, sensitive paths and critical services can be protected with explicit policies and monitoring."}] },
    work: { slug:"work", title:"Selected work and delivery experience", metaTitle:"Selected Work & E-commerce Projects | Olivon", metaDescription:"Selected Olivon web, e-commerce, migration, visibility and digital infrastructure work across Shopify, ikas, WooCommerce and custom projects.", kicker:"SELECTED WORK", lead:"Our work spans commerce builds, platform migrations, web redesigns, visibility systems and operational improvements.", sections:[{title:"Commerce projects",text:"Store architecture, catalog cleanup, integrations, migration and conversion-focused frontend work."},{title:"Growth foundations",text:"Technical SEO, analytics, structured data, content architecture and search visibility systems."},{title:"Infrastructure",text:"Cloudflare, domain, deployment and security work supporting reliable production environments."}] },
    faq: { slug:"faq", title:"Frequently asked questions", metaTitle:"FAQ | Olivon Digital Growth Studio", metaDescription:"Answers about Olivon web, e-commerce, migration, SEO, GEO, AEO, AIO, automation, project scope and international delivery.", kicker:"FAQ", lead:"Clear answers before a project starts reduce surprises later.", sections:[], faq:[["Do you work with companies outside Türkiye?","Yes. Projects can be delivered remotely for international teams, with localized content and market-specific technical requirements agreed during scoping."],["Can you handle design, development and SEO together?","Yes. We prefer to plan information architecture, design, development, analytics and search foundations as one system when the project requires it."],["Do you work with existing stores?","Yes. We can audit, redesign, migrate or improve an existing Shopify, ikas, WooCommerce or custom setup."],["How is project scope defined?","We document objectives, deliverables, assumptions, exclusions, dependencies and validation criteria before production begins."]] },
    contact: { slug:"contact", title:"Start with the problem, not the package", metaTitle:"Contact Olivon | Start a Digital Project", metaDescription:"Discuss an e-commerce, web, SEO, migration, automation or digital security project with Olivon.", kicker:"CONTACT", lead:"Share the current setup, target market, commercial objective and the constraint you need to solve. We will frame the scope from there.", sections:[{title:"Useful project context",text:"Current platform, target markets, approximate catalog size, integrations, launch target and known technical or commercial constraints help us scope accurately."},{title:"Contact",text:"Email: info@olivon.com.tr"}] }
  },
  de: {
    services:{slug:"leistungen",title:"Digitale Leistungen für Wachstum im DACH-Markt",metaTitle:"E-Commerce, Web & SEO Leistungen | Olivon",metaDescription:"E-Commerce, Webdesign, SEO, GEO, AEO, AIO, Automatisierung und Cloudflare-Sicherheit für den DACH-Markt.",kicker:"LEISTUNGEN",lead:"Wir verbinden Strategie, Commerce, Sichtbarkeit, Messung und Sicherheit in einem klar definierten Projektsystem.",sections:[{title:"E-Commerce-Infrastruktur",text:"Shopify, ikas und WooCommerce mit Produktarchitektur, Zahlung, Versand, ERP, Marktplätzen und Conversion-Messung.",bullets:["Setup und Redesign","Internationaler Commerce","SEO-sichere Migration","Integrationen"]},{title:"Suche und KI-Sichtbarkeit",text:"Technische SEO, Content-Architektur, strukturierte Daten und Entity-Signale für Google und KI-gestützte Suche."},{title:"Web, Automatisierung und Sicherheit",text:"Hochwertige Websites, kontrollierte Automatisierungen und Cloudflare-orientierte Absicherung."}]},
    ecommerce:{slug:"e-commerce-migration",title:"E-Commerce und Plattformmigration mit kontrolliertem Risiko",metaTitle:"E-Commerce & Plattformmigration DACH | Olivon",metaDescription:"Shopify, ikas und WooCommerce, internationale Store-Setups und SEO-sichere Migration mit Zahlung, Versand, ERP und Marktplätzen.",kicker:"E-COMMERCE & MIGRATION",lead:"Ein Plattformwechsel betrifft Daten, Prozesse, Sichtbarkeit und Vertrauen. Deshalb planen wir Migration und Zielsystem gemeinsam.",sections:[{title:"Plattformarchitektur",text:"Katalog, Märkte, Währungen, Customer Journey und Integrationen werden vor der Theme-Umsetzung definiert."},{title:"SEO-Migration",text:"Redirect-Mapping, Canonicals, Metadaten, Indexierungssteuerung und Crawl-Kontrolle gehören zum Migrationsplan."},{title:"Integrationen",text:"Zahlung, Versand, ERP, Marktplätze und Analytics werden an Betriebsmodell und Zielmarkt angepasst."}],faq:[["Unterstützen Sie Plattformwechsel?","Ja. Daten, URLs, Redirects und technische SEO werden gemeinsam geplant."],["Arbeiten Sie mit Shopify, ikas und WooCommerce?","Ja. Die Plattform wird nach Betriebsmodell und Integrationsbedarf bewertet."],["Sind mehrsprachige Shops möglich?","Ja, sofern Plattform und Prozesse dies sinnvoll unterstützen."]]},
    search:{slug:"seo-geo-aeo-aio",title:"SEO, GEO, AEO & AIO als zusammenhängendes Sichtbarkeitssystem",metaTitle:"SEO, GEO, AEO & AIO DACH | Olivon",metaDescription:"Technische SEO, strukturierte Daten, Entity-Signale und Antwortarchitektur für Google und KI-Suchsysteme.",kicker:"SUCHE & KI-SICHTBARKEIT",lead:"Wir machen eindeutig, wer die Marke ist, welche Leistungen sie anbietet, in welchen Märkten sie arbeitet und welche Inhalte eine konkrete Suchfrage beantworten.",sections:[{title:"Technische SEO",text:"Crawling, Indexierung, Canonicals, interne Links, Sitemap, Metadaten, Performance und strukturierte Daten."},{title:"GEO und Entity-Signale",text:"Organisation, Leistungen, Expertise und Marktbezug werden konsistent und maschinenlesbar modelliert."},{title:"AEO",text:"Wichtige Fragen werden direkt und nachvollziehbar beantwortet; FAQ- und Service-Markup wird nur dort eingesetzt, wo es inhaltlich passt."},{title:"AIO",text:"Klare Definitionen, überprüfbare Leistungsbeschreibungen und strukturierte Beziehungen verbessern die technische Grundlage für KI-gestützte Discovery."}],faq:[["Ersetzt GEO klassische SEO?","Nein. GEO baut auf sauberer technischer SEO und klaren Entity-Signalen auf."],["Garantieren Sie KI-Nennungen?","Nein. Drittanbieter-Antwortsysteme lassen sich nicht seriös garantieren."],["Implementieren Sie Schema Markup?","Ja, wenn Organization, WebSite, WebPage, Service, Breadcrumb oder FAQ den Seiteninhalt korrekt abbilden."]]},
    web:{slug:"webdesign",title:"Premium Webdesign mit technischer und kommerzieller Substanz",metaTitle:"Premium Webdesign & Entwicklung DACH | Olivon",metaDescription:"Webdesign und Entwicklung mit Mobile UX, Performance, Barrierearmut, Conversion-Architektur und technischer SEO.",kicker:"WEBDESIGN & ENTWICKLUNG",lead:"Ein hochwertiger Auftritt muss nicht nur gut aussehen, sondern verständlich, schnell und langfristig wartbar sein.",sections:[{title:"Informationsarchitektur",text:"Navigation, Seitenhierarchie, CTA und Vertrauenssignale werden aus Nutzerintentionen abgeleitet."},{title:"Mobile und Performance",text:"Responsive Verhalten, Medien, Interaktionen und Layout-Stabilität werden als Produktanforderungen behandelt."},{title:"SEO-Grundlage",text:"Metadaten, semantische Struktur, strukturierte Daten und Crawl-Pfade werden mitgedacht."}]},
    security:{slug:"sicherheit",title:"Digitale Sicherheit für geschäftskritische Websites",metaTitle:"Cloudflare & Digitale Sicherheit DACH | Olivon",metaDescription:"Cloudflare, WAF, DDoS-Schutz, Bot-Kontrolle, Zugriffsregeln und Monitoring für Websites und E-Commerce.",kicker:"DIGITALE SICHERHEIT",lead:"Sicherheitsmaßnahmen sollen Risiko reduzieren, ohne echte Nutzer oder Suchmaschinen unnötig zu blockieren.",sections:[{title:"Cloudflare",text:"DNS, SSL, WAF, Rate Controls und Traffic Policies werden an die Anwendung angepasst."},{title:"Bot-Kontrolle",text:"Automatisierter Traffic wird differenziert behandelt, damit Missbrauch reduziert und legitime Crawler erreichbar bleiben."},{title:"Zugriff und Verfügbarkeit",text:"Sensible Bereiche und administrative Zugriffe können mit klaren Policies geschützt werden."}]},
    work:{slug:"referenzen",title:"Ausgewählte Projekte und Umsetzungserfahrung",metaTitle:"Referenzen & E-Commerce Projekte | Olivon",metaDescription:"Ausgewählte Web-, E-Commerce-, Migrations-, SEO- und Infrastrukturprojekte von Olivon.",kicker:"REFERENZEN",lead:"Unsere Arbeit umfasst Commerce-Aufbau, Migration, Redesign, Sichtbarkeit und technische Infrastruktur.",sections:[{title:"Commerce",text:"Store-Architektur, Produktdaten, Integrationen, Migration und Conversion-orientiertes Frontend."},{title:"Sichtbarkeit",text:"Technische SEO, Analytics, strukturierte Daten und Content-Architektur."},{title:"Infrastruktur",text:"Cloudflare, Domain, Deployment und Sicherheitskonfiguration."}]},
    faq:{slug:"faq",title:"Häufige Fragen",metaTitle:"FAQ | Olivon Digitalstudio",metaDescription:"Antworten zu Web, E-Commerce, Migration, SEO, GEO, AEO, AIO, Automatisierung und internationaler Zusammenarbeit.",kicker:"FAQ",lead:"Klare Antworten vor Projektbeginn schaffen klare Erwartungen.",sections:[],faq:[["Arbeiten Sie mit Unternehmen außerhalb der Türkiye?","Ja. Internationale Projekte können vollständig remote umgesetzt werden."],["Können Design, Entwicklung und SEO gemeinsam geplant werden?","Ja. Genau diese gemeinsame Planung reduziert spätere technische Konflikte."],["Optimieren Sie bestehende Shops?","Ja. Audit, Redesign, Migration und technische Optimierung sind möglich."],["Wie wird der Umfang definiert?","Ziele, Deliverables, Annahmen, Ausschlüsse, Abhängigkeiten und Abnahmekriterien werden vor Produktionsstart dokumentiert."]]},
    contact:{slug:"kontakt",title:"Projekt zuerst verstehen, dann den Umfang definieren",metaTitle:"Kontakt Olivon | Digitalprojekt besprechen",metaDescription:"E-Commerce-, Web-, SEO-, Migrations-, Automatisierungs- oder Sicherheitsprojekt mit Olivon besprechen.",kicker:"KONTAKT",lead:"Nennen Sie Ausgangssystem, Zielmarkt, Geschäftsziel und den Engpass, den Sie lösen möchten.",sections:[{title:"Hilfreiche Angaben",text:"Plattform, Zielmärkte, Kataloggröße, Integrationen, Launch-Ziel und bekannte technische Anforderungen helfen bei einer präzisen Einschätzung."},{title:"Kontakt",text:"E-Mail: info@olivon.com.tr"}]}
  },
  fr: {
    services:{slug:"expertises",title:"Expertises digitales pour les marques en croissance",metaTitle:"E-commerce, Web & SEO | Expertises Olivon",metaDescription:"E-commerce, web design, SEO, GEO, AEO, AIO, automatisation et sécurité Cloudflare pour les marchés francophones.",kicker:"EXPERTISES",lead:"Nous réunissons stratégie, commerce, visibilité, mesure et sécurité dans un système de livraison cohérent.",sections:[{title:"Infrastructure e-commerce",text:"Shopify, ikas et WooCommerce avec architecture catalogue, paiement, logistique, ERP, marketplaces et mesure de conversion.",bullets:["Lancement et refonte","E-commerce international","Migration avec protection SEO","Intégrations métier"]},{title:"Visibilité Search & IA",text:"SEO technique, architecture éditoriale, données structurées et signaux d’entité pour Google et la découverte assistée par IA."},{title:"Web, automatisation et sécurité",text:"Sites premium, workflows contrôlés et sécurité centrée sur Cloudflare."}]},
    ecommerce:{slug:"e-commerce-international",title:"E-commerce international pensé pour les opérations réelles",metaTitle:"E-commerce International & Migration | Olivon",metaDescription:"Shopify, ikas, WooCommerce, lancement multi-marchés et migration SEO avec paiement, logistique, ERP et marketplaces.",kicker:"E-COMMERCE INTERNATIONAL",lead:"Vendre sur plusieurs marchés demande d’aligner plateforme, catalogue, logistique, paiements, expérience locale et migration SEO.",sections:[{title:"Architecture de plateforme",text:"Catalogue, marchés, devises, parcours client et couche d’intégration sont cadrés avant le travail de thème."},{title:"Migration SEO",text:"Redirections, canonicals, métadonnées, contrôle d’indexation et validation post-lancement font partie du plan."},{title:"Intégrations commerciales",text:"Paiement, transport, ERP, marketplaces et analytics sont adaptés au modèle opérationnel."}],faq:[["Pouvez-vous migrer une boutique existante ?","Oui. Données, URL, redirections et SEO technique sont planifiés ensemble."],["Travaillez-vous avec Shopify, ikas et WooCommerce ?","Oui. Le choix dépend du modèle opérationnel et des intégrations."],["Peut-on gérer plusieurs pays ?","Oui, lorsque la plateforme et les opérations le permettent de façon cohérente."]]},
    search:{slug:"seo-geo-aeo-aio",title:"SEO, GEO, AEO & AIO dans un même système de visibilité",metaTitle:"SEO, GEO, AEO & AIO | Olivon",metaDescription:"SEO technique, données structurées, signaux d’entité et architecture de réponse pour Google et les moteurs assistés par IA.",kicker:"SEARCH & VISIBILITÉ IA",lead:"Nous structurons les informations pour rendre explicites la marque, ses services, ses marchés et les réponses qu’elle apporte aux recherches importantes.",sections:[{title:"SEO technique",text:"Crawl, indexation, canonicals, maillage interne, sitemap, métadonnées, performance et données structurées."},{title:"GEO et entités",text:"Organisation, services, expertise et zones desservies sont reliés par des signaux cohérents et lisibles par machine."},{title:"AEO",text:"Les questions commerciales importantes reçoivent des réponses directes et structurées, avec FAQ ou Service schema lorsque c’est pertinent."},{title:"AIO",text:"Définitions claires, preuves concrètes et relations structurées créent une meilleure base pour la découverte assistée par IA."}],faq:[["Le GEO remplace-t-il le SEO ?","Non. Le GEO repose sur une base SEO solide et une entité clairement définie."],["Garantissez-vous des citations par les IA ?","Non. Aucun prestataire sérieux ne peut garantir le comportement de moteurs tiers."],["Ajoutez-vous les données structurées ?","Oui, lorsque Organization, WebSite, WebPage, Service, Breadcrumb ou FAQ correspondent réellement au contenu."]]},
    web:{slug:"web-design",title:"Web design premium avec une vraie architecture commerciale",metaTitle:"Web Design Premium & Développement | Olivon",metaDescription:"Sites corporate et e-commerce premium avec UX mobile, performance, accessibilité, conversion et fondations SEO techniques.",kicker:"WEB DESIGN & DÉVELOPPEMENT",lead:"L’esthétique compte, mais l’architecture sous-jacente détermine si le site reste rapide, clair et utile dans le temps.",sections:[{title:"Architecture de l’information",text:"Navigation, hiérarchie, CTA et preuves de confiance sont structurés selon les intentions des utilisateurs."},{title:"Mobile et performance",text:"Responsive, médias, interactions et stabilité visuelle sont traités comme des exigences produit."},{title:"Livraison orientée recherche",text:"Métadonnées, structure sémantique, données structurées et chemins de crawl sont intégrés."}]},
    security:{slug:"securite-digitale",title:"Sécurité digitale pour les sites qui doivent rester disponibles",metaTitle:"Cloudflare & Sécurité Digitale | Olivon",metaDescription:"Cloudflare, WAF, protection DDoS, contrôle des bots, politiques d’accès et monitoring pour les sites critiques.",kicker:"SÉCURITÉ DIGITALE",lead:"La sécurité doit réduire le risque sans dégrader les parcours clients ni bloquer le trafic légitime.",sections:[{title:"Protection Cloudflare",text:"DNS, SSL, WAF, rate controls et politiques de trafic sont configurés selon le comportement réel du site."},{title:"Bots et abus",text:"Le trafic automatisé est segmenté pour limiter les abus tout en maintenant l’accès des moteurs légitimes."},{title:"Accès et continuité",text:"Les zones sensibles et accès administratifs peuvent être protégés par des politiques explicites."}]},
    work:{slug:"realisations",title:"Réalisations sélectionnées et expérience de livraison",metaTitle:"Réalisations Web & E-commerce | Olivon",metaDescription:"Sélection de projets Olivon en e-commerce, migration, web, visibilité et infrastructure digitale.",kicker:"RÉALISATIONS",lead:"Nos missions couvrent e-commerce, migration, refonte, visibilité organique et infrastructure technique.",sections:[{title:"Commerce",text:"Architecture de boutique, données produit, intégrations, migration et frontend orienté conversion."},{title:"Visibilité",text:"SEO technique, analytics, données structurées et architecture éditoriale."},{title:"Infrastructure",text:"Cloudflare, domaine, déploiement et sécurité."}]},
    faq:{slug:"faq",title:"Questions fréquentes",metaTitle:"FAQ | Olivon Studio Digital",metaDescription:"Réponses sur le web, l’e-commerce, la migration, le SEO, GEO, AEO, AIO, l’automatisation et les projets internationaux.",kicker:"FAQ",lead:"Des réponses claires avant le projet permettent de mieux cadrer la livraison.",sections:[],faq:[["Travaillez-vous avec des entreprises hors de Türkiye ?","Oui. Les projets internationaux peuvent être menés entièrement à distance."],["Pouvez-vous gérer design, développement et SEO ensemble ?","Oui. Cette approche évite de traiter la recherche et la technique trop tard."],["Intervenez-vous sur des boutiques existantes ?","Oui. Audit, refonte, migration et optimisation sont possibles."],["Comment définissez-vous le périmètre ?","Objectifs, livrables, hypothèses, exclusions, dépendances et critères de validation sont documentés avant la production."]]},
    contact:{slug:"contact",title:"Commencer par le problème, pas par un forfait",metaTitle:"Contact Olivon | Parler de votre projet",metaDescription:"Présentez votre projet e-commerce, web, SEO, migration, automatisation ou sécurité digitale à Olivon.",kicker:"CONTACT",lead:"Partagez la plateforme actuelle, le marché cible, l’objectif commercial et la contrainte principale à résoudre.",sections:[{title:"Informations utiles",text:"Plateforme, marchés, taille du catalogue, intégrations, objectif de lancement et contraintes techniques permettent un cadrage plus précis."},{title:"Contact",text:"E-mail : info@olivon.com.tr"}]}
  }
};

export const intlPageKeys = Object.keys(intlPages.en) as IntlPageKey[];

export function pageKeyFromSlug(locale: Locale, slug: string): IntlPageKey | null {
  for (const key of intlPageKeys) if (intlPages[locale][key].slug === slug) return key;
  return null;
}

export function localizedPath(locale: Locale, key: IntlPageKey) {
  return `/${locale}/${intlPages[locale][key].slug}`;
}
