export const referenceProjects = [
  {
    name: "Öykü Baby Store",
    domain: "oykubabystore.com.tr",
    url: "https://oykubabystore.com.tr/",
    image: "/images/references/oyku-baby-store.png?v=20260910-1",
    category: "Bebek & çocuk giyim",
    scope: "E-ticaret deneyimi, vitrin kurgusu, ürün sunumu",
    featured: true,
  },
  {
    name: "Bailas Kids",
    domain: "bailaskids.com",
    url: "https://bailaskids.com/",
    image: "/images/references/bailas-kids.png?v=20260910-1",
    category: "Çocuk giyim",
    scope: "Premium vitrin, kategori akışı, satış odaklı arayüz",
    featured: true,
  },
  {
    name: "Favorim Kids",
    domain: "favorimkids.com",
    url: "https://favorimkids.com/",
    image: "/images/references/favorim-kids.png?v=20260910-1",
    category: "Çocuk giyim & kombin",
    scope: "E-ticaret kurgu, görsel düzen, alışveriş yolculuğu",
    featured: true,
  },
  { name: "Recep Bozkurt", domain: "recepbozkurt.com", url: "https://recepbozkurt.com/", category: "E-ticaret", scope: "WooCommerce tabanlı uçtan uca e-ticaret altyapısı, ürün ve satış akışı" },
  { name: "Sporfit Korse", domain: "sporfitkorse.com", url: "https://sporfitkorse.com/", category: "Korse & spor ürünleri", scope: "E-ticaret ve satış altyapısı" },
  { name: "Velista", domain: "velista.com.tr", url: "https://velista.com.tr/", category: "Moda", scope: "E-ticaret ve ürün deneyimi" },
  { name: "Hiranur", domain: "hiranur.com.tr", url: "https://hiranur.com.tr/", category: "Moda & perakende", scope: "Web/e-ticaret düzenleme" },
  { name: "Bohem Kids", domain: "bohemkids.com", url: "https://bohemkids.com/", category: "Çocuk giyim", scope: "E-ticaret sunum düzeni" },
  { name: "Nully Moda", domain: "nullymoda.com", url: "https://nullymoda.com/", category: "Moda", scope: "Satış odaklı web deneyimi" },
  { name: "Glory Wears", domain: "glorywears.com", url: "https://glorywears.com/", category: "Moda", scope: "E-ticaret vitrini" },
  { name: "By Derya Avcı", domain: "byderyaavci.com", url: "https://byderyaavci.com/", category: "Moda & marka", scope: "Web ve marka görünürlüğü" },
  { name: "Miladeren Butik", domain: "miladerenbutik.com", url: "https://miladerenbutik.com/", category: "Butik", scope: "E-ticaret düzenleme" },
  { name: "Kayseri As Tesisat", domain: "kayseriastesisat.com.tr", url: "https://kayseriastesisat.com.tr/", category: "Yerel hizmet", scope: "Kurumsal web ve yerel görünürlük" },
  { name: "Ayfa Tesisat", domain: "ayfatesisat.com", url: "https://www.ayfatesisat.com/", category: "Yerel hizmet", scope: "Kurumsal web deneyimi" },
  { name: "Ejder Dekorasyon", domain: "ejderdekorasyon.com", url: "https://ejderdekorasyon.com/", category: "Dekorasyon", scope: "Kurumsal web ve hizmet sunumu" },
  { name: "IGM Women", domain: "igmwomen.com", url: "https://igmwomen.com/", category: "Kadın moda", scope: "E-ticaret ve marka vitrini" },
  { name: "Formtime Shopping", domain: "formtimeshopping.com", url: "https://formtimeshopping.com/", category: "Alışveriş", scope: "E-ticaret deneyimi" },
];
