export const serviceGroups = [
  {
    slug: "e-ticaret-sistemleri",
    href: "/hizmetler/e-ticaret",
    title: "E-ticaret sistemleri",
    intro: "Shopify, ikas ve WooCommerce altyapılarında satışa hazır, yönetilebilir ve büyümeye açık mağazalar kurar; gerektiğinde platformlar arası geçişi veri ve SEO kaybını azaltacak şekilde yönetiriz.",
    image: "/images/services/e-ticaret-sistemleri.webp?v=20260910-2",
    items: ["Platform seçimi", "ikas · Shopify · WooCommerce platform taşıma", "Pazaryerinden kendi e-ticaret sitesine geçiş", "Ödeme, kargo, ERP ve pazaryeri entegrasyonu", "Kategori ve ürün mimarisi"],
  },
  {
    slug: "ikas-kurulum-destek",
    href: "/ikas",
    title: "ikas kurulum & destek",
    intro: "ikas partner yapısıyla mağazanızı strateji, görsel, içerik ve operasyon tarafıyla birlikte ele alırız.",
    image: "/images/services/ikas-kurulum-destek.webp?v=20260910-2",
    items: ["Strateji ve yol haritası", "Slider, banner ve ürün görsel desteği", "Sanal POS, ERP ve kargo bağlantıları", "Check-up ve iyileştirme raporu"],
  },
  {
    slug: "web-tasarim-gelistirme",
    href: "/hizmetler/web-tasarim",
    title: "Web tasarım & geliştirme",
    intro: "Kurumsal web siteleri, landing page’ler ve dönüşüm odaklı arayüzleri marka algısını güçlendirecek şekilde tasarlarız.",
    image: "/images/services/web-tasarim-gelistirme.webp?v=20260910-2",
    items: ["Kurumsal site", "Landing page", "Mobil deneyim", "Performans ve teknik altyapı"],
  },
  {
    slug: "seo-geo-aeo-aio",
    href: "/hizmetler/seo-geo-aeo-aio",
    title: "SEO, GEO, AEO & AIO",
    intro: "Google’da, yerel aramalarda ve yapay zekâ cevap motorlarında doğru anlaşılmanız için içerik ve teknik temel kurarız.",
    image: "/images/services/seo-geo-aeo-aio.webp?v=20260910-2",
    items: ["Teknik SEO", "İçerik mimarisi", "Yapılandırılmış veri", "AI arama görünürlüğü"],
  },
  {
    slug: "dijital-reklam-marka",
    href: "/hizmetler/dijital-reklam",
    title: "Dijital reklam & marka pazarlama",
    intro: "Meta, Google ve pazaryeri kampanyalarını trafik değil; kârlılık, veri ve marka güveni üzerinden yönetiriz.",
    image: "/images/services/dijital-reklam-marka.webp?v=20260910-2",
    items: ["Kampanya stratejisi", "Kreatif yönlendirme", "Dönüşüm ölçümü", "Kârlılık analizi"],
  },
  {
    slug: "dijital-guvenlik",
    href: "/hizmetler/dijital-guvenlik",
    title: "Dijital güvenlik",
    intro: "Cloudflare, WAF, bot kontrolü, erişim politikaları ve izleme kurgusuyla web varlıklarınızı daha güvenli hale getiririz.",
    image: "/images/services/dijital-guvenlik.webp?v=20260910-2",
    items: ["DDoS koruma", "WAF kuralları", "Bot ve trafik kontrolü", "Erişim güvenliği"],
  },
];

export const ikasMenuItems = [
  { label: "Strateji", slug: "strateji" },
  { label: "Görsel destek", slug: "gorsel-destek" },
  { label: "Kargo entegrasyonu", slug: "kargo-entegrasyonu" },
  { label: "E-ihracat çözümleri", slug: "e-ihracat-cozumleri" },
  { label: "Front-end ve back-end", slug: "front-end-back-end" },
  { label: "Sabit sayfalar", slug: "sabit-sayfalar" },
  { label: "Sanal POS entegrasyonu", slug: "sanal-pos-entegrasyonu" },
  { label: "Pazaryeri entegrasyonu", slug: "pazaryeri-entegrasyonu" },
];
